import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [dog , setDog] = useState(null)

  const fetchRandomdog = async () =>{
    const res = await fetch("https://dog.ceo/api/breeds/image/random");
    const data = await res.json()

    setDog(data)
  }

  useEffect(() => {
    fetchRandomdog()
  } , [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello dog</h1>
      <button onClick={fetchRandomdog}>Get Random dog</button>

      {dog && <Image src={dog.message} width={200} height={200} alt="" />}
      
      </>
  )
}
